# ONE-SHOT generator, not a build step. Extracts EPA's prose from the archived
# source Word document and writes it to narrative_generated.md for manual
# assembly into index.qmd.
#
#   "C:\Program Files\R\R-4.5.3\bin\Rscript.exe" R/gen_narrative.R
#
# Requires the archive at the path below (not part of this repo, see
# data-raw/PROVENANCE.md). Once index.qmd is edited and signed off, the docx
# is out of the loop: index.qmd is the source of truth from then on, and
# rerunning this script does not overwrite it. This script exists so the
# extraction is reproducible and auditable, not so it runs on every build.
#
# One correction is applied after extraction, not before, and is called out
# below: two URLs in the Data Sources paragraph differ between this archived
# docx (dated 2024-07-08) and the actually published page (verified live,
# January 2025 snapshot). The rest of the docx's text was cross-checked
# paragraph by paragraph against the live page and matched exactly, so this
# is treated as a post-docx web-only edit, not an extraction error.

source(here::here("R/utils/read_docx.R"))

ARCHIVE_DOCX <- paste0(
  "C:/Users/alyko/Desktop/archive/",
  "Word Files - Indicator Text and TD  (for published indicator updates as of 7-23-2026)/",
  "Heat-related deaths/heat-deaths_text_07-08-24.docx"
)

if (!file.exists(ARCHIVE_DOCX)) {
  stop(
    "Archive not found at:\n  ", ARCHIVE_DOCX,
    "\nThis script is a one-shot generator; see data-raw/PROVENANCE.md.",
    call. = FALSE
  )
}

df <- read_docx_paragraphs(ARCHIVE_DOCX)

get <- function(rng) paste(df$text_md[rng], collapse = "\n\n")

# Verified against the live published page (indices confirmed by heading match
# in the docx and by cross-checking every paragraph but the two URLs below).
background          <- get(4:6)
about_the_indicator  <- get(8:10)
key_points           <- df$text_md[12:18]
indicator_notes      <- get(32:35)
data_sources         <- get(37)
references_raw       <- df$text_md[39:57]

# Correction: the archived docx (2024-07-08) names two CDC URLs that the
# published page (verified live, epa.gov January 2025 snapshot) has since
# updated. Every other word in this paragraph matched the live page exactly,
# so this is a targeted fix, not a re-extraction.
data_sources <- sub(
  "www.cdc.gov/environmental-health-tracking/about/index.html",
  "www.cdc.gov/nceh/tracking", data_sources, fixed = TRUE
)
data_sources <- sub(
  "https://wonder.cdc.gov/mcd.html", "https://wonder.cdc.gov/mcd-icd10.html",
  data_sources, fixed = TRUE
)

# References: strip the leading "N. " (already asserted 1:19 in order below),
# emit as raw HTML <ol> with id="ref-N" anchors so body superscripts can link
# to them. The words are untouched; only the markup changes.
ref_num <- as.integer(sub("^(\\d{1,2})\\..*$", "\\1", references_raw))
stopifnot("reference numbers are not 1:19 in order" = identical(ref_num, 1:19))
ref_text <- sub("^\\d{1,2}\\.\\s*", "", references_raw)
references_html <- paste0(
  '<ol class="references">\n',
  paste0('  <li id="ref-', ref_num, '">', ref_text, "</li>", collapse = "\n"),
  "\n</ol>"
)

# Body superscript reference markers, e.g. "^9,10^", become links to those
# anchors: "[9](#ref-9),[10](#ref-10)" wrapped back in superscript markup.
sup_to_links <- function(x) {
  m <- gregexpr("\\^[0-9,]+\\^", x)
  regmatches(x, m) <- lapply(regmatches(x, m), function(hits) {
    vapply(hits, function(h) {
      nums <- strsplit(sub("^\\^", "", sub("\\^$", "", h)), ",")[[1]]
      linked <- paste0("[", nums, "](#ref-", nums, ")", collapse = ",")
      paste0("^", linked, "^")
    }, character(1))
  })
  x
}
background          <- sup_to_links(background)
about_the_indicator  <- sup_to_links(about_the_indicator)
key_points           <- sup_to_links(key_points)
indicator_notes      <- sup_to_links(indicator_notes)
data_sources         <- sup_to_links(data_sources)

out <- c(
  "<!-- Generated by R/gen_narrative.R from the archived source docx.",
  "     This is a one-shot output for hand-assembly into index.qmd, not",
  "     itself rendered. See R/gen_narrative.R for the URL correction",
  "     applied to Data Sources. -->",
  "",
  "## Key Points", "",
  paste0("- ", key_points, collapse = "\n\n"), "",
  "## Background", "",
  background, "",
  "## About the Indicator", "",
  about_the_indicator, "",
  "## Indicator Notes", "",
  indicator_notes, "",
  "## Data Sources", "",
  data_sources, "",
  "## References", "",
  references_html, ""
)

writeLines(out, here::here("narrative_generated.md"), useBytes = TRUE)
cat("Wrote narrative_generated.md,", length(out), "lines.\n")
