# Extract EPA's published prose for the Heat-Related Deaths indicator and
# write it to narrative.qmd.
#
#   Rscript R/gen_narrative.R
#
# Source is data-raw/heat-deaths_text_07-08-24.docx (vendored, scrubbed of
# reviewer-identifying metadata; see data-raw/PROVENANCE.md and
# R/scrub_docx.R). data-raw/heat-deaths_TD_06-02-24 CLEAN.docx is also
# vendored for provenance but not read here: unlike cold-related-deaths, this
# indicator has no supplementary figure whose title/caption lives only in the
# technical documentation.
#
# One correction is applied after extraction, not before, and is called out
# below: two URLs in the Data Sources paragraph differ between this docx
# (dated 2024-07-08) and the actually published page (verified live, January
# 2025 snapshot). The rest of the docx's text was cross-checked paragraph by
# paragraph against the live page and matched exactly, so this is treated as a
# post-docx web-only edit, not an extraction error.

root <- here::here()
source(file.path(root, "R", "utils", "read_docx.R"))
source(file.path(root, "R", "utils", "write_stable.R"))

raw_dir  <- file.path(root, "data-raw")
TEXT_DOCX <- file.path(raw_dir, "heat-deaths_text_07-08-24.docx")
OUT_QMD   <- file.path(root, "narrative.qmd")

if (!file.exists(TEXT_DOCX)) {
  stop("Source document not found: ", TEXT_DOCX, call. = FALSE)
}

df  <- read_docx_paragraphs(TEXT_DOCX)
sec <- docx_sections(df)

get <- function(rng) paste(df$text_md[rng], collapse = "\n\n")

title    <- df$text_plain[1]
subtitle <- df$text_plain[2]

# Key Points is a bulleted list; the section's raw paragraph range also
# contains the Figure 1/Figure 2 title/caption/source blocks that Word placed
# after the bullets and before "Indicator Notes", so bullets are selected by
# style within that range rather than by taking the whole range verbatim.
kp_idx     <- sec[["Key Points"]]
key_points <- df$text_md[kp_idx][df$style[kp_idx] == "Bullet2" & !df$empty[kp_idx]]

background          <- get(sec[["Background"]])
about_the_indicator <- get(sec[["About the Indicator"]])
indicator_notes     <- get(sec[["Indicator Notes"]])
data_sources        <- get(sec[["Data Sources"]])

# Correction: the docx (2024-07-08) names two CDC URLs that the published page
# (verified live, epa.gov January 2025 snapshot) has since updated. Every
# other word in this paragraph matched the live page exactly, so this is a
# targeted fix, not a re-extraction.
data_sources <- sub(
  "www.cdc.gov/environmental-health-tracking/about/index.html",
  "www.cdc.gov/nceh/tracking", data_sources, fixed = TRUE
)
data_sources <- sub(
  "https://wonder.cdc.gov/mcd.html", "https://wonder.cdc.gov/mcd-icd10.html",
  data_sources, fixed = TRUE
)

# References: this document cites sources with typed superscript numbers, not
# real Word endnotes (contrast cold-related-deaths, which has
# w:endnoteReference markers). Numbers are already 1:19 in document order.
references_idx <- sec[["References"]]
references_idx <- references_idx[!df$empty[references_idx]]
references_raw <- df$text_md[references_idx]
ref_num  <- as.integer(sub("^(\\d{1,2})\\..*$", "\\1", references_raw))
stopifnot("reference numbers are not 1:19 in order" = identical(ref_num, 1:19))
ref_text <- sub("^\\d{1,2}\\.\\s*", "", references_raw)
references_html <- paste0(
  '<ol class="references">\n',
  paste0('  <li id="ref-', ref_num, '">', ref_text, "</li>", collapse = "\n"),
  "\n</ol>"
)

# Body superscript reference markers, e.g. "^9,10^", become links to those
# anchors: "[9](#ref-9),[10](#ref-10)" wrapped back in superscript markup.
sup_to_links <- function(x) {
  m <- gregexpr("\\^[0-9,]+\\^", x)
  regmatches(x, m) <- lapply(regmatches(x, m), function(hits) {
    vapply(hits, function(h) {
      nums <- strsplit(sub("^\\^", "", sub("\\^$", "", h)), ",")[[1]]
      linked <- paste0("[", nums, "](#ref-", nums, ")", collapse = ",")
      paste0("^", linked, "^")
    }, character(1))
  })
  x
}
background          <- sup_to_links(background)
about_the_indicator  <- sup_to_links(about_the_indicator)
key_points           <- sup_to_links(key_points)
indicator_notes      <- sup_to_links(indicator_notes)
data_sources         <- sup_to_links(data_sources)

out <- c(
  "---",
  paste0('title: "', title, '"'),
  paste0('subtitle: "', subtitle, '"'),
  "---",
  "",
  "<!-- Generated by R/gen_narrative.R from data-raw/heat-deaths_text_07-08-24.docx.",
  "     Do not edit by hand: rerunning the generator overwrites this file. -->",
  "",
  "## Key Points", "",
  paste0("- ", key_points, collapse = "\n\n"), "",
  "## Background", "",
  background, "",
  "## About the Indicator", "",
  about_the_indicator, "",
  "## Indicator Notes", "",
  indicator_notes, "",
  "## Data Sources", "",
  data_sources, "",
  "## References", "",
  references_html, ""
)

write_lines_stable(out, OUT_QMD)
assert_clean_output(OUT_QMD)

cat("Wrote", basename(OUT_QMD), "-", length(out), "lines,",
    length(ref_num), "references.\n")
